[project]
name = "omnipresenseradar"
version = "0.1.0"
description = "A comprehensive, type-safe Python interface for OmniPreSense radar sensors"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pyserial>=3.5"]
